import pickle

fakeNews1 = '''A recently leaked internal memo reveals that several major news outlets have been covertly collaborating with political lobbyists to shape public opinion on key social issues. According to whistleblower testimony, editorial guidelines are being manipulated to favor narratives that align with powerful interest groups, effectively turning trusted media platforms into propaganda machines. Experts warn this undermines journalistic integrity and could drastically shift upcoming election outcomes by skewing voter perceptions.'''
fakeNews2 = '''Apple Unveils Revolutionary Contact Lenses Capable of Projecting Augmented Reality Experiences Directly Onto the User's Retina, Marking a Major Leap Forward in Wearable Technology.'''
fakeNews3 = '''US to Replace Immigration Interviews with AI-Powered Lie-Detecting Dogs. In a bold new initiative to streamline visa processing, the Department of Homeland Security has announced it will roll out a fleet of genetically modified beagles trained to sniff out "visa fraud vibes" using AI-enhanced olfactory systems. The dogs, dubbed “Visabarkers,” will reportedly replace human officers in 30% of consular interviews by next year. Officials claim early tests show the dogs have a 93% accuracy rate in detecting nervous applicants, though critics warn this could violate civil liberties and the Americans with Disabilities Act. PETA and the ACLU have already filed joint lawsuits.'''
fakeNews4 = '''Leonardo da Vinci's Last Invention Found: Blueprint for Wi-Fi.'''

realNews1 = '''US President Donald Trump has accused China of violating a two-week-old truce on tariffs - a sign trade tensions between the world\'s two largest economies could again escalate.  Washington and Beijing agreed to temporarily lower tit-for-tat tariffs after talks in Geneva earlier this month.  Trump said on Friday in a Truth Social post that tariffs had left China in "grave economic danger", before the countries had made a "fast deal".  However he said China had "totally violated its agreement with us", without explaining how.  US Trade Representative Jamieson Greer later said China had not been removing non-tariff barriers in the way that had been agreed. Beijing is yet to respond to the claims.'''
realNews2 = '''US to double tariffs on steel and aluminium imports to 50%, Trump says.President Donald Trump has announced the US will double its current tariff rate on steel and aluminium imports from 25% to 50%, starting on Wednesday.  Speaking at a rally in Pittsburgh, Pennsylvania on Friday, Trump said the move would help boost the local steel industry and national supply, while reducing reliance on China.  Trump also said that $14bn would be invested in the area's steel production through a partnership between US Steel and Japan's Nippon Steel, though he later told reporters he had yet to see or approve the final deal.'''
realNews3 = '''India says over 1,000 nationals deported by US since January. More than a thousand Indians have "come back or [been] deported" from the United States since January, India\'s foreign ministry has said.  Spokesperson Randhir Jaiswal said that around 62% of them came on commercial flights, without providing more details.  This comes in the wake of President Donald Trump\'s campaign against undocumented migrants to the US. Trump had earlier said that India "will do what\'s right" on the deportation of illegal migrants.'''
realNews4 = '''Astronauts in space for nine months didn't know if they would 'be able to make it back'. When astronauts Suni Williams and Butch Wilmore approached the International Space Station (ISS) last year with failing thrusters on their Boeing Starliner capsule, they were unable to fly forward to dock.  And if they couldn\'t dock, they didn\'t know if they could make it back home again.  "Docking was imperative," Mr Wilmore told BBC News, two months after he and Ms Williams finally made a successful return to Earth. "If we weren\'t able to dock, would we be able to make it back? We didn\'t know."  The astronauts had been travelling on a test flight that was meant to last eight days. Instead, they ended up staying in space for nearly 10 months.'''

fakeNews = [fakeNews1, fakeNews2, fakeNews3, fakeNews4]
realNews = [realNews1, realNews2, realNews3, realNews4]

filename = "testcases.bin"
with open(filename, 'wb') as file:
    pickle.dump({'fakeNews': fakeNews, 'realNews': realNews}, file)
